(()=>{
  function ensure(){if(!s.skippedLessons||typeof s.skippedLessons!=='object')s.skippedLessons={}}
  const key=(p,i)=>`${p.id}:${i}`;const isSkipped=(p,i)=>{ensure();return !!s.skippedLessons[key(p,i)]};
  function nextIndex(p){return p.lessons.findIndex((_,i)=>!s.done[key(p,i)]&&!isSkipped(p,i))}
  function pendingSkipped(p){return p.lessons.map((_,i)=>i).filter(i=>!s.done[key(p,i)]&&isSkipped(p,i))}
  function decorate(){ensure();const p=phaseObj(),rows=[...document.querySelectorAll('#lessonList .lesson')];rows.forEach((row,i)=>{const k=key(p,i),done=!!s.done[k],skipped=!done&&isSkipped(p,i);row.style.opacity=skipped?'.72':'';let wrap=row.querySelector('.lessonSkipWrap');if(!wrap){wrap=document.createElement('div');wrap.className='lessonSkipWrap';wrap.style.cssText='display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-left:auto';row.appendChild(wrap)}wrap.innerHTML='';if(skipped){const pill=document.createElement('span');pill.className='pill';pill.textContent='Skipped for now';wrap.appendChild(pill)}const b=document.createElement('button');b.type='button';b.className='btn';b.textContent=done?'Completed':skipped?'Resume lesson':'Skip for now';b.disabled=done;b.onclick=e=>{e.preventDefault();e.stopPropagation();if(skipped)delete s.skippedLessons[k];else s.skippedLessons[k]=true;save()};wrap.appendChild(b);const check=row.querySelector('[data-lesson]');if(check){const old=check.onchange;check.onchange=()=>{if(check.checked)delete s.skippedLessons[k];if(old)old()}}});const ni=nextIndex(p),pending=pendingSkipped(p);if(ni>=0){q('#nextAction').textContent=`Next: ${p.lessons[ni]}`;q('#heroLine').textContent=`${p.id}: ${p.lessons[ni]}`}else if(pending.length){q('#nextAction').textContent=`All currently unskipped lessons are done. Resume one of ${pending.length} skipped lesson${pending.length>1?'s':''} before this phase can be truly complete.`;q('#heroLine').textContent=`${p.id}: ${pending.length} skipped lesson${pending.length>1?'s':''} still incomplete.`}}
  const baseRender=render;render=function(){baseRender();decorate()};
  function whatNow(){const p=phaseObj(),i=nextIndex(p),pending=pendingSkipped(p);alert(i>=0?`Do this next:\n${p.lessons[i]}\n\nThen practice it and mark it complete.`:pending.length?`You have ${pending.length} skipped lesson${pending.length>1?'s':''} to return to before this phase is complete.`:'This phase is complete. Move forward or finish the Bridge readiness checks.')}
  function rebuild(){const p=phaseObj(),i=nextIndex(p),pending=pendingSkipped(p);s.tasks=i>=0?[{text:`Learn: ${p.lessons[i]}`,pom:1,done:false},{text:`Practice: ${p.lessons[i]}`,pom:2,done:false},{text:'Verify output and save evidence if useful',pom:1,done:false}]:pending.length?[{text:`Resume skipped lesson: ${p.lessons[pending[0]]}`,pom:1,done:false},{text:'Complete its practice and verify the result',pom:2,done:false}]:[{text:'Review phase evidence and readiness',pom:1,done:false}];save()}
  function initHandlers(){const w=q('#whatNowBtn'),r=q('#rebuildTasksBtn');if(w)w.onclick=whatNow;if(r)r.onclick=rebuild}
  ensure();initHandlers();
})();
