(()=>{
  const TIMER_KEY='daMentorBridge.timer.v2';
  const ensure=()=>{if(!Array.isArray(s.focusSessions))s.focusSessions=[]};ensure();
  const modeDuration=m=>m==='focus'?Math.max(10,+s.focusMin||25):m==='short'?Math.max(1,+s.shortMin||5):Math.max(5,+s.longMin||15);
  const makeIdle=(m='focus')=>({v:2,status:'idle',mode:m,durationMin:modeDuration(m),remainingSec:modeDuration(m)*60,startedAt:0,endAt:0,phase:'',sessionId:'',completedAt:0});
  const loadTimer=()=>{try{const x=JSON.parse(localStorage.getItem(TIMER_KEY)||'null');return x&&x.v===2?Object.assign(makeIdle(x.mode||'focus'),x):makeIdle()}catch(e){return makeIdle()}};let T=loadTimer();
  const store=()=>localStorage.setItem(TIMER_KEY,JSON.stringify(T));const persist=()=>localStorage.setItem(KEY,JSON.stringify(s));const rem2=()=>T.status==='running'?Math.max(0,Math.ceil((T.endAt-Date.now())/1000)):Math.max(0,+T.remainingSec||0);const fmt=x=>`${String(Math.floor(x/60)).padStart(2,'0')}:${String(Math.floor(x%60)).padStart(2,'0')}`;
  const logged=id=>s.focusSessions.some(x=>x&&x.sessionId===id);
  const askNotification=()=>{try{if('Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{})}catch(e){}};
  const signal=async(title,body)=>{if(s.alarm!=='on')return;try{if(navigator.vibrate)navigator.vibrate([180,80,180,80,260])}catch(e){}try{const A=window.AudioContext||window.webkitAudioContext,ctx=new A(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=780;g.gain.value=.06;o.start();setTimeout(()=>{o.stop();ctx.close()},500)}catch(e){}try{if('Notification'in window&&Notification.permission==='granted'){if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,tag:'mentor-focus-complete',renotify:true})}else new Notification(title,{body})}}catch(e){}};
  function draw(){const clock=q('#timerClock'),start=q('#timerStart'),hint=q('#timerHint');if(!clock||!start)return;clock.textContent=T.status==='complete'?'00:00':fmt(rem2());start.textContent=T.status==='running'?'PAUSE':T.status==='complete'?'DONE':'START';qa('[data-timer-mode]').forEach(b=>b.classList.toggle('active',b.dataset.timerMode===T.mode));if(hint)hint.textContent=T.status==='complete'?`✅ ${T.mode==='focus'?`${T.durationMin}m focus saved to Reports`:'Break complete'} — tap DONE`:T.mode==='focus'?`${s.focusMin}m focus • ${s.shortMin}m short • ${s.longMin}m long${T.status==='running'?' • background-safe tracking':''}`:'Breaks do not add to study time.';q('#focusPill').textContent=`${minsToday()}m focus today`;q('#focusToday').textContent=`${minsToday()}m`;let target=Math.round((+s.dailyTarget||2)*60);q('#targetText').textContent=`${minsToday()}/${target}m`;q('#targetBar').style.width=Math.min(100,minsToday()/Math.max(1,target)*100)+'%';q('#targetSummary').textContent=minsToday()>=target?'Daily target reached.':`${Math.max(0,target-minsToday())} minutes remaining today.`}
  function reset(m=T.mode){if(timer){clearInterval(timer);timer=null}T=makeIdle(m);mode=m;seconds=T.remainingSec;store();draw()}
  async function complete(){if(T.status==='complete')return;ensure();const id=T.sessionId||`bridge-${T.startedAt||Date.now()}`,minutes=+T.durationMin||modeDuration(T.mode),phase=T.phase||s.phase||'B01',focus=T.mode==='focus';if(focus&&!logged(id)){s.focusLog[today()]=(s.focusLog[today()]||0)+minutes;s.focusSessions.push({sessionId:id,date:today(),minutes,phase,startedAt:T.startedAt||0,completedAt:Date.now()});persist();render()}T.status='complete';T.remainingSec=0;T.endAt=0;T.completedAt=Date.now();T.sessionId=id;store();draw();await signal(focus?'Focus session complete':'Break complete',focus?`${minutes} minutes saved to DA Mentor Bridge reports.`:'Your break is finished.')}
  function reconcile(){if(T.status==='running'&&rem2()<=0)complete();else draw()}
  function toggle(){if(T.status==='complete'){reset(T.mode);return}if(T.status==='running'){T.remainingSec=rem2();T.status='paused';T.endAt=0;store();draw();return}const wasPaused=T.status==='paused',secs=wasPaused&&T.remainingSec>0?T.remainingSec:modeDuration(T.mode)*60;T.status='running';T.durationMin=wasPaused?(+T.durationMin||modeDuration(T.mode)):modeDuration(T.mode);T.remainingSec=secs;T.startedAt=T.startedAt||Date.now();T.endAt=Date.now()+secs*1000;T.phase=T.phase||s.phase||'B01';T.sessionId=T.sessionId||`bridge-${T.startedAt}-${Math.random().toString(36).slice(2,8)}`;store();askNotification();draw()}
  function setMode(m){if(!['focus','short','long'].includes(m))return;reset(m)}
  function install(){if(timer){clearInterval(timer);timer=null}mode=T.mode;seconds=rem2();qa('[data-timer-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.timerMode));q('#timerStart').onclick=toggle;q('#timerReset').onclick=()=>reset(T.mode);resetClock=()=>reset(T.mode);q('#saveSettingsBtn')?.addEventListener('click',()=>setTimeout(()=>{if(T.status==='idle')reset(T.mode);else draw()},0));['pageshow','focus','online'].forEach(ev=>window.addEventListener(ev,reconcile));document.addEventListener('visibilitychange',reconcile);setInterval(reconcile,1000);reconcile()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
