(()=>{
  const KEY2='daMentorBridge.studySession.v1';
  const load=()=>{try{return Object.assign({active:false,startedAt:0,phase:'',sessionId:''},JSON.parse(localStorage.getItem(KEY2)||'{}'))}catch(e){return {active:false,startedAt:0,phase:'',sessionId:''}}};let S=load();const persistSession=()=>localStorage.setItem(KEY2,JSON.stringify(S));
  const fmtElapsed=ms=>{const total=Math.floor(Math.max(0,ms)/1000),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),sec=total%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`};const elapsed=()=>S.active?Date.now()-S.startedAt:0;const startLabel=()=>S.startedAt?new Date(S.startedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'';
  function ensureSessions(){if(!Array.isArray(s.focusSessions))s.focusSessions=[]}
  function installUI(){const card=document.querySelector('.focusTimerCard');if(!card)return;const h=card.querySelector('h2');if(h)h.textContent='Manual study session';const shell=card.querySelector('.timerShell');if(!shell)return;shell.innerHTML=`<div class="muted tiny">Use your phone Clock for Pomodoro alarms. Mentor records only between START STUDY and END STUDY.</div><div class="focusClock" id="studySessionClock">00:00</div><div class="row timerControls"><button class="btn primary" id="studySessionToggle">START STUDY</button><button class="btn" id="studySessionCancel">Cancel</button></div><div class="muted tiny topGap" id="studySessionHint"></div>`;document.getElementById('studySessionToggle').onclick=toggle;document.getElementById('studySessionCancel').onclick=cancel;draw()}
  function draw(){const c=document.getElementById('studySessionClock'),b=document.getElementById('studySessionToggle'),x=document.getElementById('studySessionCancel'),h=document.getElementById('studySessionHint');if(!c||!b)return;c.textContent=fmtElapsed(elapsed());b.textContent=S.active?'END STUDY':'START STUDY';if(x)x.disabled=!S.active;if(h)h.textContent=S.active?`Started ${startLabel()} • reopening Mentor will not end it.`:'Session ends only when you press END STUDY.'}
  function start(){S={active:true,startedAt:Date.now(),phase:s.phase||'B01',sessionId:`bridge-study-${Date.now()}-${Math.random().toString(36).slice(2,8)}`};persistSession();draw()}
  function end(){if(!S.active)return;ensureSessions();const ended=Date.now(),minutes=Math.max(1,Math.round((ended-S.startedAt)/60000)),id=S.sessionId;if(!s.focusSessions.some(x=>x&&x.sessionId===id)){s.focusLog[today()]=(s.focusLog[today()]||0)+minutes;s.focusSessions.push({sessionId:id,date:today(),minutes,phase:S.phase||s.phase||'B01',startedAt:S.startedAt,completedAt:ended,source:'manual-study-session'})}S={active:false,startedAt:0,phase:'',sessionId:''};persistSession();localStorage.setItem(KEY,JSON.stringify(s));render();draw();alert(`Study session saved: ${minutes>=60?`${Math.floor(minutes/60)}h ${minutes%60}m`:`${minutes}m`}.`)}
  function toggle(){S.active?end():start()}function cancel(){if(!S.active)return;if(!confirm('Cancel this active study session without saving it?'))return;S={active:false,startedAt:0,phase:'',sessionId:''};persistSession();draw()}function reconcile(){S=load();draw()}
  function init(){installUI();window.addEventListener('focus',reconcile);window.addEventListener('pageshow',reconcile);document.addEventListener('visibilitychange',reconcile);setInterval(draw,1000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
